concurrency: slow-itests
jobs:
  Run-CoreNLP-Slow-Tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: "echo \"\U0001F389 The job was automatically triggered by a ${{ github.event_name\
        \ }} event.\""
    - continue-on-error: true
      run: "echo \"\U0001F427 This job is now running on a ${{ runner.os }} server\
        \ hosted by GitHub!\""
    - continue-on-error: true
      run: "echo \"\U0001F50E The name of your branch is ${{ github.ref }} and your\
        \ repository is ${{ github.repository }}.\""
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v2
    - continue-on-error: true
      run: "echo \"\U0001F4A1 The ${{ github.repository }} repository has been cloned\
        \ to the runner.\""
    - continue-on-error: true
      run: "echo \"\U0001F5A5\uFE0F The workflow is now ready to test your code on\
        \ the runner.\""
    - continue-on-error: true
      name: Setup
      run: 'pwd

        ant clean compile

        echo $CLASSPATH

        echo $PATH

        '
    - continue-on-error: true
      if: always()
      name: Run Misc Slow Tests
      run: 'ant itest-misc

        '
    - continue-on-error: true
      if: always()
      name: Run KBP Tests
      run: 'ant itest-kbp

        '
    - continue-on-error: true
      if: always()
      name: Run NER Tests
      run: 'ant itest-ner

        '
    - continue-on-error: true
      if: always()
      name: Run Coref Tests
      run: 'ant itest-coreference

        '
    - continue-on-error: true
      if: always()
      name: Run Many Docs Tests
      run: 'ant itest-many-docs

        '
    - continue-on-error: true
      if: always()
      name: Run Protobuf Slow Test
      run: 'ant itest-protobuf

        '
    - continue-on-error: true
      run: echo "All tests finished!"
    - continue-on-error: true
      run: "echo \"\U0001F34F This job's status is ${{ job.status }}.\""
    timeout-minutes: 2880
name: Run Slow Tests
on:
  repository_dispatch:
    types: trigger-ga___run-slow-itests.yaml
